port:  5000
markdown: kramdown
name: "CivicEngager"
url: http://civicengager.com
encoding: utf-8
timezone: America/NewYork
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyDO5-7togIhNMVcJbrVBO7aLrf35FMBQeMx
