port:  5000
markdown: kramdown
name: "CivicEngager"
url: http://www.civicengager.com
encoding: utf-8
timezone: America/NewYork
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyBXYiqDHGvNgnMEeGeA_0q8cz53DXrBCyE
